batch_size: 32   # 1 for evaluation, 64 for training
beta1: 0.9
chosen_label: 0
cloud_center: false
cloud_noise: false
cloud_noise_scale: 0.002
cloud_random_rotate: false
cloud_recenter2orig: false
cloud_rescale2orig: false
cloud_scale: true
cloud_scale_scale: 2.0
cloud_size: 4000
cloud_translate: false
cloud_translate_shift:
- 0.00055863
- 0.00127477
- 0.01701898
cycle_length: 400
deterministic: false
distributed: True
g_latent_space_size: 32
g_posterior_n_layers: 1
g_prior_n_features: 64
g_prior_n_flows: 3
c_prior_dims: 5
cond_type: 'continuous'
gent_weight: 0.1
gnll_weight: 0.1
jobid: '1'
logging: false
logging_img: true
logging_img_frequency: 1
logging_path: /home/damoda95/Upload/results/airplane_gen_model
max_beta2: 0.99
max_lr: 0.000256
meshes_fname: ShapeNetCore55v2_meshes_resampled.h5
min_beta2: 0.99
min_lr: 0.000256
model_name: generative_model_airplane_pretrained.pkl
n_components: 4
n_epochs: 800
num_workers: 1
p_decoder_base_type: free
p_decoder_base_var: -3.9551
p_decoder_n_features: 64
p_decoder_n_flows: 14
p_latent_space_size: 6
p_prior_n_layers: 1
params_reduce_mode: depth_and_feature
path2data: D:\Masters\Univerities\TU Dresden\Post_Admit\Studies\4th Sem\RP\data
path2save: /home/damoda95/Uplaod/results/airplane_gen_model]
pc_enc_init_n_channels: 6
pc_enc_init_n_features: 64
pc_enc_n_features:
- 16
- 32
- 64
pnll_weight: 0.5
resume: false
resume_optimizer: false
saving_mode: true
shuffle: true
train_mode: p_rnvp_mc_g_rnvp_vae
util_mode: training
wd: 1.0e-06
weights_type: learned_weights

experiment_path: "/path_to_def"